//@/app/tech-stack/stackData.ts
/*role : Données de la stack technique
   import : aucun (fichier de données brut)
   useBy : app/tech-stack/page.tsx
*/

export interface TechItem {
  id: string;
  name: string;
  category: string;
  iconName: string; // nom de l'icône Lucide (ex: 'Server', 'Layout', ...)
  description: string;
  features: string[];
  color: string; // classe Tailwind pour le fond de l'icône
  docs: string;
  cmdI: string; // commande npm d'installation
}

export const techStack: TechItem[] = [
  {
    id: 'nextjs',
    name: 'Next.js 16',
    category: 'Framework',
    iconName: 'Server',
    description: 'Framework React full-stack avec App Router, Server Components et Server Actions.',
    features: ['App Router', 'Server Components', 'Server Actions', 'Turbopack'],
    color: 'bg-black/5 dark:bg-white/5',
    docs: 'https://nextjs.org/docs',
    cmdI: 'npx create-next-app@latest',
  },
  {
    id: 'react',
    name: 'React 19',
    category: 'Framework',
    iconName: 'Layout',
    description: 'Bibliothèque pour construire des interfaces utilisateur avec une architecture à base de composants.',
    features: ['Composants fonctionnels', 'Hooks', 'Concurrent Mode', 'Server Components'],
    color: 'bg-blue-500/10 dark:bg-blue-500/20',
    docs: 'https://react.dev',
    cmdI: 'npm install react react-dom',
  },
  {
    id: 'typescript',
    name: 'TypeScript 5',
    category: 'Langage',
    iconName: 'ShieldCheck',
    description: 'Superset typé de JavaScript qui apporte une sécurité et une robustesse accrues.',
    features: ['Typage strict', 'Inférence', 'Generics', 'Union/Intersection'],
    color: 'bg-blue-600/10 dark:bg-blue-600/20',
    docs: 'https://www.typescriptlang.org',
    cmdI: 'npm install -D typescript @types/react @types/node',
  },
  {
    id: 'zustand',
    name: 'Zustand',
    category: 'State Management',
    iconName: 'Database',
    description: 'Gestion d\'état minimaliste, performante et scalable avec une API simple.',
    features: ['Store simple', 'Mutative', 'Middleware', 'Devtools'],
    color: 'bg-amber-500/10 dark:bg-amber-500/20',
    docs: 'https://zustand-demo.pmnd.rs',
    cmdI: 'npm install zustand',
  },
  {
    id: 'react-hook-form',
    name: 'React Hook Form',
    category: 'Formulaires',
    iconName: 'FormInput',
    description: 'Gestion de formulaires performante et flexible avec validation intégrée.',
    features: ['Validation synchrone/asynchrone', 'Gestion d\'erreurs', 'Mode contrôlé/non contrôlé'],
    color: 'bg-pink-500/10 dark:bg-pink-500/20',
    docs: 'https://react-hook-form.com',
    cmdI: 'npm install react-hook-form',
  },
  {
    id: 'zod',
    name: 'Zod',
    category: 'Validation',
    iconName: 'ShieldCheck',
    description: 'Bibliothèque de validation de schémas TypeScript-first avec inférence de types.',
    features: ['Schémas simples', 'Validation personnalisée', 'Inférence TypeScript'],
    color: 'bg-sky-500/10 dark:bg-sky-500/20',
    docs: 'https://zod.dev',
    cmdI: 'npm install zod',
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS 4',
    category: 'Styling',
    iconName: 'Paintbrush',
    description: 'Framework CSS utilitaire qui permet de construire des designs personnalisés rapidement.',
    features: ['Classes utilitaires', 'Dark mode', 'Responsive', 'Personnalisation'],
    color: 'bg-cyan-500/10 dark:bg-cyan-500/20',
    docs: 'https://tailwindcss.com',
    cmdI: 'npm install tailwindcss @tailwindcss/postcss',
  },
  {
    id: 'shadcn',
    name: 'shadcn/ui',
    category: 'UI Components',
    iconName: 'Layers',
    description: 'Collection de composants React réutilisables, accessibles et personnalisables.',
    features: ['Accès à la source', 'Customisation', 'Accessibilité', 'Dark mode'],
    color: 'bg-primary/10',
    docs: 'https://ui.shadcn.com',
    cmdI: 'npx shadcn@latest init',
  },
  {
    id: 'lucide',
    name: 'Lucide Icons',
    category: 'Icons',
    iconName: 'Sparkles',
    description: 'Bibliothèque d\'icônes SVG modernes, légères et cohérentes pour React.',
    features: ['Plus de 1000 icônes', 'Personnalisables', 'Tree-shakable'],
    color: 'bg-rose-500/10 dark:bg-rose-500/20',
    docs: 'https://lucide.dev',
    cmdI: 'npm install lucide-react',
  },
  {
    id: 'dnd-kit',
    name: 'dnd-kit',
    category: 'Drag & Drop',
    iconName: 'Workflow',
    description: 'Bibliothèque de drag & drop moderne, performante et accessible pour React.',
    features: ['Drag & drop', 'Accessibilité', 'Performance', 'Personnalisation'],
    color: 'bg-violet-500/10 dark:bg-violet-500/20',
    docs: 'https://dndkit.com',
    cmdI: 'npm install @dnd-kit/core @dnd-kit/sortable @dnd-kit/utilities',
  },
  {
    id: 'shiki',
    name: 'Shiki',
    category: 'Code Highlighting',
    iconName: 'Code',
    description: 'Moteur de coloration syntaxique précis (basé sur VS Code) idéal pour afficher des extraits de code.',
    features: ['Thèmes VS Code', 'Server Components', 'Haute précision', 'Build-time'],
    color: 'bg-emerald-500/10 dark:bg-emerald-500/20',
    docs: 'https://shiki.style',
    cmdI: 'npm install shiki',
  },
  {
    id: 'prisma',
    name: 'Prisma',
    category: 'ORM / Database',
    iconName: 'Database',
    description: 'ORM TypeScript-first pour interagir facilement et en toute sécurité avec la base de données.',
    features: ['Schéma déclaratif', 'Migrations', 'Type-safety', 'Prisma Client'],
    color: 'bg-indigo-500/10 dark:bg-indigo-500/20',
    docs: 'https://www.prisma.io/docs',
    cmdI: 'npm install prisma @prisma/client && npx prisma init',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'Paiements',
    iconName: 'CreditCard',
    description: 'Solution de paiement complète pour gérer les transactions, abonnements et checkouts e-commerce.',
    features: ['Checkout', 'Elements', 'Webhooks', 'Abonnements'],
    color: 'bg-violet-600/10 dark:bg-violet-600/20',
    docs: 'https://stripe.com/docs',
    cmdI: 'npm install stripe @stripe/stripe-js @stripe/react-stripe-js',
  },
  {
    id: 'better-auth',
    name: 'Better Auth',
    category: 'Authentification',
    iconName: 'Lock',
    description: 'Bibliothèque d\'authentification moderne, type-safe et self-hosted pour Next.js.',
    features: ['Email/Password', 'OAuth', 'Sessions', 'Plugins (2FA, Passkeys)'],
    color: 'bg-green-500/10 dark:bg-green-500/20',
    docs: 'https://www.better-auth.com',
    cmdI: 'npm install better-auth',
  },
  {
    id: 'tanstack-query',
    name: 'TanStack Query',
    category: 'Data Fetching',
    iconName: 'RefreshCw',
    description: 'Gestion puissante du cache et des données asynchrones côté client.',
    features: ['Cache intelligent', 'Refetch automatique', 'Optimistic updates', 'Devtools'],
    color: 'bg-red-500/10 dark:bg-red-500/20',
    docs: 'https://tanstack.com/query',
    cmdI: 'npm install @tanstack/react-query',
  },
  {
    id: 'resend',
    name: 'Resend',
    category: 'Email',
    iconName: 'Mail',
    description: 'Service d\'envoi d\'emails transactionnels moderne avec excellent support React.',
    features: ['React Email', 'Templates', 'Deliverability', 'API simple'],
    color: 'bg-orange-500/10 dark:bg-orange-500/20',
    docs: 'https://resend.com/docs',
    cmdI: 'npm install resend',
  },
  {
    id: 'framer-motion',
    name: 'Framer Motion',
    category: 'Animation',
    iconName: 'Move',
    description: 'Bibliothèque d\'animations déclarative et performante pour React.',
    features: ['Gestures', 'Layout animations', 'Variants', 'Exit animations'],
    color: 'bg-purple-500/10 dark:bg-purple-500/20',
    docs: 'https://www.framer.com/motion',
    cmdI: 'npm install framer-motion',
  },
  // === NOUVELLES BIBLIOTHÈQUES AJOUTÉES ===
  {
    id: 'chalk',
    name: 'Chalk',
    category: 'Utilities',
    iconName: 'Terminal',
    description: 'Permet de styliser les logs dans la console avec des couleurs et du style pour une meilleure lisibilité.',
    features: ['Couleurs', 'Styles (gras, italique)', 'Chaînes de caractères', 'Personnalisation'],
    color: 'bg-teal-500/10 dark:bg-teal-500/20',
    docs: 'https://github.com/chalk/chalk',
    cmdI: 'npm install chalk',
  },
  {
    id: 'date-fns',
    name: 'date-fns',
    category: 'Date & Time',
    iconName: 'Calendar',
    description: 'Bibliothèque légère et moderne pour manipuler et formater les dates en JavaScript.',
    features: ['Formatage', 'Comparaison', 'Manipulation', 'Tree-shakable'],
    color: 'bg-blue-400/10 dark:bg-blue-400/20',
    docs: 'https://date-fns.org',
    cmdI: 'npm install date-fns',
  },
  {
    id: 'chartjs',
    name: 'Chart.js',
    category: 'Charts & Data',
    iconName: 'BarChart3',
    description: 'La bibliothèque de graphiques la plus populaire, flexible et interactive pour afficher des données.',
    features: ['8 types de graphiques', 'Animations', 'Responsive', 'Interactions'],
    color: 'bg-rose-400/10 dark:bg-rose-400/20',
    docs: 'https://www.chartjs.org',
    cmdI: 'npm install chart.js react-chartjs-2',
  },
];